GET http://localhost:5285/genre

###
GET http://localhost:5285/genre/7

###
POST http://localhost:5285/genre/add
Content-Type:  application/json

{
    "name" : "Children's"
}

###
PATCH  http://localhost:5285/genre/7
Content-Type:  application/json

{
    "name" : "baby"
}

###
DELETE  http://localhost:5285/genre/6
