GET http://localhost:5285/games

###
GET http://localhost:5285/games/3

###
GET http://localhost:5285/games/active

###
GET http://localhost:5285/games/inActive

###
POST http://localhost:5285/games/add
Content-Type: application/json

{
    "name": "Half-Life",
    "genre": "Shooter",
    "price": 34.99,
    "releaseDate": "1998-11-19"
}


###
PATCH  http://localhost:5285/games/7
Content-Type: application/json

{
    "price": 89.99
}


###
DELETE   http://localhost:5285/games/7
Content-Type: application/json

{
    "price": 89.99
}


